name: csc1016863
channels:
  - conda-forge
  - defaults
  - nvidia
dependencies:
  - pip
  - python=3.9
  - pip:
      - stable-baselines3==2.0.0a5
      - swig
      - gymnasium[atari]
      - gymnasium[accept-rom-license]
      - imageio
      - mlflow
      - opencv-python
      - optuna
      - IPython
      - imageio[ffmpeg]
      - imageio[pyav]
      - torch==1.12.1
      - torchaudio==0.12.1
      - torchvision==0.13.1