env_id: ALE/Pacman-v5
eval_frequency: 25000
experiment_name: PacManA2C_Tuned
hyperparameters:
  ent_coef: 0.0033
  gamma: 0.99592
  learning_rate: 5.1e-05
  max_grad_norm: 0.274
  n_steps: 45
  policy: CnnPolicy
  verbose: 1
model_architecture: A2C
n_envs: 4
n_stack: 4
steps_to_train: 10000000
