env_id: BreakoutNoFrameskip-v4
eval_frequency: 25000
experiment_name: BreakoutDQN_Tuned
hyperparameters:
  buffer_size: 100000
  exploration_final_eps: 0.02594
  exploration_fraction: 0.01572
  exploration_initial_eps: 0.025999
  learning_rate: 8.3e-05
  policy: CnnPolicy
  train_freq: 8
  verbose: 1
model_architecture: DQN
n_envs: 4
n_stack: 4
steps_to_train: 10000000
