env_id: PongNoFrameskip-v4
eval_frequency: 25000
experiment_name: PongDQN_Tuned
hyperparameters:
  buffer_size: 100000
  exploration_final_eps: 0.00101
  exploration_fraction: 0.03571
  exploration_initial_eps: 0.1215
  learning_rate: 8.8e-05
  policy: CnnPolicy
  train_freq: 2
  verbose: 1
model_architecture: DQN
n_envs: 4
n_stack: 4
steps_to_train: 10000000
