env_id: SpaceInvadersNoFrameskip-v4
eval_frequency: 25000
experiment_name: SpaceInvadersDQN_Tuned
hyperparameters:
  buffer_size: 100000
  exploration_final_eps: 0.02736
  exploration_fraction: 0.04786
  exploration_initial_eps: 0.030902
  learning_rate: 2.7e-05
  policy: CnnPolicy
  train_freq: 8
  verbose: 1
model_architecture: DQN
n_envs: 4
n_stack: 4
steps_to_train: 10000000
